services:
  kafka:
    build: kafka
    hostname: kafka
    ports:
      - 9092:9092
  producer:
    image: producer:0.0.1-SNAPSHOT
    hostname: producer
    ports:
      - 8080:8080
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
